### ISSUE TITLE
Ошибка: сервер разрывает соединение при неправильном вводе логина или пароля

### ISSUE THREAD

**Issue by Frosty1cat** [werryxgames/Messenger#10]
Опишите шаги для повторения ошибки
1. откройте messenger как обычно
2. введите неправильно логин или пароль
3. Готово. Сервер разорвал соединение

**Ожидаемое поведение**
Что должно было случиться? Ничего.

**Скриншоты**
Если возможно, прикрепите скриншоты (снимки экрана).

**Информация об устройстве:**
 - Устройство: (ПК)
 - ОС: (Windows 10)
 - Версия: (v.x.x если существует тэг, или ID коммита)

**Дополнительная информация**
Любая другая информация

**Comment by werryxgames** [comment]
Исправлено

**Comment by Frosty1cat** [comment]
неа

**Comment by werryxgames** [comment]
Попробуйте заново скачать новейшую версию Messenger
