### ISSUE TITLE
Ошибка: не удается найти пользователя

### ISSUE THREAD

**Issue by Frosty1cat** [werryxgames/Messenger#13]
**Опишите ошибку**
Я попытался найти друга и не получилось

**Повторение ошибки**
Опишите шаги для повторения ошибки:
1.введите в окне поиска ник вашего только зарегистрировавшегося друга
2. попробуйте добавить
3. готово. сервер пишет что не удалось найти

**Ожидаемое поведение**
друг должен был добавится в контакты

**Скриншоты**

**Информация об устройстве:**
 - Устройство: (ПК)
 - ОС: (Windows 10)

**Дополнительная информация**
Любая другая информация
![Снимок экрана 2022-10-18 184504](https://user-images.githubusercontent.com/115944585/196479388-41569cb1-d787-4691-a34c-54154bfd8573.png)

**Comment by werryxgames** [comment]
Нет, только один должен включить server.py, а второй должен указать IP адрес сервера в client.py как я писал

**Comment by Frosty1cat** [comment]
что за клиент

**Comment by Frosty1cat** [comment]
а белый ip это публичный?

**Comment by Frosty1cat** [comment]
просто я дал другу мой публичный ip и не получилось

**Comment by Frosty1cat** [comment]
он его там указал в мэин

**Comment by Frosty1cat** [comment]
и в итоге ничего не получилось

**Comment by Frosty1cat** [comment]
109.252.149.199

**Comment by Frosty1cat** [comment]
и что

**Comment by Frosty1cat** [comment]
ау

**Comment by werryxgames** [comment]
Если ваш друг указал этот IP адрес в main.py вместо 127.0.0.1 и всё равно не получается, то попробуйте сделать переадресацию портов на роутере (если не знаете как, то поищите в интернете). Необходимо открыть порт 7505 для UDP
